### ISSUE TITLE
Active Color of Labels

### ISSUE THREAD

**Issue by pheinecke** [amdelamar/pm-theme#10]
The color of the currently selected label in the menu bar is white for the flat theme. Makes it hard to read in front of the light background. I think the font-style should be consistent with the other menu items.

**Comment by amdelamar** [comment]
Ok should be fixed now. 

If you're using CSS import you might have to add a `?v=1.1` to the address like so:

`@import url("https://amdelamar.github.io/pm-theme/themes/pm-flat-theme.css?v=1.1");`

Otherwise, just copy/paste the CSS contents!

**Comment by pheinecke** [comment]
Yep, fixed. Thanks.
