### ISSUE TITLE
Color selector in composer shows --theme1 color

### ISSUE THREAD

**Issue by Rafficer** [amdelamar/pm-theme#20]
## Your Environment

 * Theme used: Tested with dark and gm
 * Browser name and version: Firefox 57
 * OS/Device version: Win10

## What is the Problem?

Color selector in composer shows the --theme1 color and not the colors of the fields.

![image](https://user-images.githubusercontent.com/19485606/34327030-55a5ed62-e8ba-11e7-8385-3c3f760ad975.png)

**Comment by amdelamar** [comment]
Ok should be fixed now. Remember to add a "?v=20" or other tag on the end to bypass the browser cache, if you're using the `@import` statement.
