### ISSUE TITLE
Dark Theme Horizontal Layout Issues 

### ISSUE THREAD

**Issue by 5car1z** [amdelamar/pm-theme#21]
## Your Environment

 * Theme used: "Dark Theme"
 * Browser name and version: Google Chrome Version 64.0.3282.85 (Official Build) beta (64-bit)

## What is the Problem?

Email entries in the "horizontal layout" (toggle view) are obfuscated and barely visible, as of the 15/16th January. Vertical layout seem's fine, or "better". The dark colouring has also changed substantially. 

This is on both Windows 7 and Xubuntu 16.04.3 desktop machines. It's the same for me in Chrome, Firefox, and Brave web browsers. 

![](https://i.gyazo.com/38801b249cf8a742cdc6a6595e0a4a6f.png)

I'm using `@import url("https://austindelamar.com/pm-theme/themes/pm-dark-theme.min.css");` in the settings custom theme box.

**Comment by 5car1z** [comment]
There seems to be similar problems in the `Settings" page(s) as well.

**Comment by amdelamar** [comment]
Ok, might get time later today to fix...

**Comment by amdelamar** [comment]
Ok should be patched up again.

To update, and get around your browser cache, you can append a variable `?v=23` to the end of the URL, like so:

```css
/* Copy this line into ProtonMail's custom theme box: */
@import url("https://austindelamar.com/pm-theme/themes/pm-dark-theme.css?v=23");
```

Or if you copied the source directly, you'll have to copy the updated source again.

**Comment by seevee** [comment]
This works for me in Electron/Chromium, thanks @amdelamar!

**Comment by 5car1z** [comment]
Works fine for me too in the initially quoted browsers. 

Thanks for fixing this so promptly! Really great theme.
