### ISSUE TITLE
Link editor in composer bad colors

### ISSUE THREAD

**Issue by Rafficer** [amdelamar/pm-theme#23]
## Your Environment

 * Theme used: PM-Dark
 * Browser name and version: Firefox 57.0.4
 * OS/Device version: Windows 10

## What is the Problem?

The link editor in the composer for both emails and signatures is hard to read. When writing something in the textboxes it's white on white and can't be read.

![image](https://user-images.githubusercontent.com/19485606/35091310-8cfdebd0-fc3c-11e7-9752-634f0a7cd326.png)

**Comment by amdelamar** [comment]
Ok fixed. And a few other things too, like close/minimize button borders, and insert images.

To update, and get around your browser cache, you can append a variable `?v=23b` to the end of the URL, like so:

```css
/* Copy this line into ProtonMail's custom theme box: */
@import url("https://austindelamar.com/pm-theme/themes/pm-dark-theme.css?v=23b");
```

Or if you copied the source directly, you'll have to copy the updated source again.

**Comment by amdelamar** [comment]
In your case, RawGit link:

```css
@import url("https://cdn.rawgit.com/amdelamar/pm-theme/master/themes/pm-dark-theme.min.css");
```

**Comment by Rafficer** [comment]
Awesome, thanks a lot!

**Comment by Rafficer** [comment]
Composer is fixed, however signature editor (Settings > Name / Signature > Edit Signature) is not. 

![image](https://user-images.githubusercontent.com/19485606/35167336-60f05ac2-fd55-11e7-80c4-81e1a130eacf.png)

**Comment by amdelamar** [comment]
Ok try now

**Comment by Rafficer** [comment]
Works with austindelamar.com already. rawgit has some delay still I think.

Awesome, thanks!
