### ISSUE TITLE
Update to v3.13.0 // Correct colors for Shift + Tab command line

### ISSUE THREAD

**Issue by Rafficer** [amdelamar/pm-theme#28]
New PM version with new features. 

Shift + Tab command window text isn't readable with dark theme. Colors need to be adapted.

![x](https://i.imgur.com/TsZlTez.png)

![x](https://i.imgur.com/z1cyRuJ.png)

**Comment by amdelamar** [comment]
Ok I'll see what I can do

**Comment by Rafficer** [comment]
Thank you (:

**Comment by amdelamar** [comment]
Should be fixed now

**Comment by Rafficer** [comment]
Looks good, thank you :)
