### ISSUE TITLE
PM Flat - label disappear when clicking on them

### ISSUE THREAD

**Issue by ntimo** [amdelamar/pm-theme#3]
Hi their,
when I click onto a label in the sidebar their text color changes to white. So I can't read that anymore. I hope you could maybe fix this in your css code :)

Have a nice start into the new year!
Timo

**Comment by amdelamar** [comment]
Good catch! I will fix it soon.

**Comment by amdelamar** [comment]
Ok. I have it patched in bf77b26.  I've also added some **bold** to labels when selected.

**Comment by ntimo** [comment]
Hi,
thank you for fixing it. And Happy new Year :)
