### ISSUE TITLE
Add Unpkg CDN link

### ISSUE THREAD

**Issue by amdelamar** [amdelamar/pm-theme#31]
First, this depends on NPM publish.

But then, the unpkg link would be as simple as:

https://unpkg.com/pm-theme@3.13.1/themes/pm-dark-theme.min.css

**Comment by MartinKolarik** [comment]
You could also just make a GitHub release and then use https://cdn.jsdelivr.net/gh/amdelamar/pm-theme@3.13.1/themes/pm-dark-theme.min.css

**Comment by ColinMaudry** [comment]
What about https://raw.githubusercontent.com/amdelamar/pm-theme@3.13.1/themes/pm-dark-theme.min.css ?

**Comment by amdelamar** [comment]
@MartinKolarik Yes, I think I'd have to add GitHub releases to my workflow. Does jsDeliver work well for CSS projects?

@ColinMaudry There is a [RawGit](https://rawgit.com/) tool you can use. For example:
```
https://cdn.rawgit.com/amdelamar/pm-theme/c023ddef/themes/bg-image-theme.min.css
```

**Comment by MartinKolarik** [comment]
@amdelamar not necessarily GitHub releases, git tags created from the command line should work too. Works great for anything hosted either on npm or GitHub.
