### ISSUE TITLE
Folder indicator at top of email wrong colors

### ISSUE THREAD

**Issue by amdelamar** [amdelamar/pm-theme#37]
## Your Environment
 * Theme used: (Dark / Flat / GM / BG-Image)

## Describe the Problem

Looking at an email in a folder, the folder indicator at the top has the wrong bg color.

**Comment by joelbduncan** [comment]
This makes the BG colour correct but I think it needs to match the style of the other dropdowns where
only the text highlight

![proton-dropdown-bg-colour](https://user-images.githubusercontent.com/1405445/43453819-fba87514-94b2-11e8-87ad-49c63d17ebb6.png)

```
.pm_dropdown {
	background: var(--theme3)!important;
}
```

**Comment by amdelamar** [comment]
@Slethen Thanks for the comment. ~Can you open a new issue for it?~ I opened an issue for this #39
