### ISSUE TITLE
White around time/date in meta infomation in PM 3.14

### ISSUE THREAD

**Issue by joelbduncan** [amdelamar/pm-theme#38]
## Your Environment
 * Theme used: (Dark / Flat / GM / BG-Image): Dark
 * Browser name and version: Firefox 61.0.1
 * OS/Device version: Pop!_OS

## Describe the Problem
White around time/date in meta infomation in ProtonMail 3.14.

This fixes it but wasn't sure how to incorporate it into your CSS

```
.summary-right {
	background: var(--theme3)!important;
}
```

Before

![white-space-meta](https://user-images.githubusercontent.com/1405445/43454018-9ef9bef8-94b3-11e8-9c3c-df3e52623fc9.png)

After

![white-space-meta-after](https://user-images.githubusercontent.com/1405445/43454167-154e4362-94b4-11e8-960f-9d64b3bbc932.png)

**Comment by joelbduncan** [comment]
Awesome job! I've found some other oddities would you like me to create individual issues for them?

**Comment by amdelamar** [comment]
Yes, absolutely
