### ISSUE TITLE
PM Flat - Filter labels input

### ISSUE THREAD

**Issue by ntimo** [amdelamar/pm-theme#4]
Hi,
When entering something into the label search box the background colour changes to white. This looks really crazy. Here is a screenshot of the behaviour. And also sorry for the wrong issue title.

<img width="204" alt="bildschirmfoto 2017-01-01 um 16 08 12" src="https://cloud.githubusercontent.com/assets/6145026/21582656/d6299f46-d061-11e6-888f-b6a58c322df0.png">

**Comment by amdelamar** [comment]
Ok. I've pushed the fix for this in 361d942 and also corrected the unread/read button background color.
Thanks!
