### ISSUE TITLE
GM conversation border and bg

### ISSUE THREAD

**Issue by Kuchiru** [amdelamar/pm-theme#41]
## Your Environment
 * Theme used: (GM)
 * Browser name and version: Chrome 68.0.3440.106
 * OS/Device version: macOS 10.13.6

It seems there has been an update in the PM CSS that broke some of the elements, i'm unable to figure this out unfortunately :(

![screen shot 2018-08-14 at 08 50 13](https://user-images.githubusercontent.com/7408353/44076066-1f6c3a98-9f9f-11e8-9a50-21285f39514a.jpg)

**Comment by JeGr** [comment]
Wanted to report the same thing. It only happens in the wide layout selection as this uses other CSS class combinations as the horizontal splitted view.

The unread mail entries have the wrong BG color, font color and the first and last three colums seem to have double bottom border lines as well as the tag/folder BG color.

I'd also would find it extremely nice, if (perhaps a copy/fork of) that theme could support background images like the current GMail implementation (and add the more round-ish looks of the current layout).

Happy to help somehow!

**Comment by JeGr** [comment]
In addition to that, the "star" button on the right side of the "subject" line, is cut. The right side has no line and no margin to the side. ~5px too far right indifferent what view (with preview panel or without) one chooses.

**Comment by amdelamar** [comment]
Thanks for the notes @JeGr. I haven't had time for quite a while to fix this and need to get back into it. (I'll accept PRs!) 

If you find other separate problems, you can open new issues for them, as this gives better visibility to the number of problems open.

**Comment by JeGr** [comment]
I'd try a PR but ATM in too many projects. Hopefully find the time later otherwise just have to wait for you :)

As I've found other things, I'll pack those in a separate issue
