### ISSUE TITLE
@import blocked by Content-Security-Policy

### ISSUE THREAD

**Issue by amdelamar** [amdelamar/pm-theme#42]
## Your Environment
 * Theme used: (Dark / Flat / GM / BG-Image)
 * Browser name and version: Firefox 60
 * OS/Device version: 

## Describe the Problem

Using `@import` doesn't work anymore. The default `default-src 'self';` security policy of the page is blocking the loading of remote content (CSS).

**Comment by Garbee** [comment]
The only thing that can be done to "bypass" CSP in this context is making an extension to auto-inject the styles.

Best path forward, remove the import mentions and inform users that they need to just copy & paste the source into their settings.
