### ISSUE TITLE
Minor CSS style bugs/improvements in GM theme

### ISSUE THREAD

**Issue by JeGr** [amdelamar/pm-theme#43]
## Your Environment
 * Theme used: GM
 * Browser name and version:  Chrome 69/win64
 * OS/Device version: Windows 10/64

## Describe the Problem

I've found a few additional bugs and perhaps improvements of the GM theme:

1. Left and top bar: The gray used could/should perhaps be a little darker each. The left one and the red font on the bottom don't match that well - the contrast is a bit too low so it's hard to read. So I changed theme2 to #3f3f40 and theme5 to #696a6c. That's a personal thing obviously but as I worked in webdesign, those minor things (like color matching/blocking) nag a bit on me ;) Just thinking those two changes would appear in a bit more harmonious default

2. Settings / Dashboard: The red "Info" text next to the (i) Button for more information on the professional option have borders around. Those aren't nice to look at nor are they in the default theme.

3. Settings / Folders/Labels: (and any page with toggles) The toggles have a fine border and background around them. Shouldn't be there. Edit & Delete Buttons have no spacing between them and look crowded.

4. Settings / Filters: Same as 3, toggles with borders, three buttons on the right with no spacing. Also the Whitelist Buttons for move and delete look too big and crowded with the box border.

5. Settings / Autorespond: Biggest issue with the toggle background and border as it get's stretched the whole 50% grid and interferes with the "Answer" text on the right if enabled.

6. Settings / Security: The toggles again ;)

7. Settings / Design: Toggles! And didn't notice it before but the Dropdowns all look like white text boxes, the down arrow seems missing. And for german text the last box (left to right) is too narrow. Did a quick test and it seems the "z-index: 3" is the problem with the missing arrow.

8. Settings / Payment: The download buttons again shows it's a tad too big and touches the bottom divider line so it just looks "crowded". Either adding margin:2px to .pm_button or reducing it's height and line-height from 34 to ~30 would do fine.

But even if that list starts sounding like nitpicking, I just want to say a big thank you, as the all-around quality of the theme/changes is amazing and makes using protonmail much more fun (for me at least) and eye-candy ;)

Greets,
Jens

**Comment by amdelamar** [comment]
Thanks. I fixed everything that I could. Although, I'm not sure about # 7 in your list. If you want to upload a screencap it might help. Otherwise checkout the latest version and see if that fixes everything.

Note, The themes are color based changes only. So anything to do with spacing/border/layout/position/icons are probably bugs with PM's web app, and could be filed on their repo here: https://github.com/protonmail/webclient and help them out.

**Comment by JeGr** [comment]
Awesome, had it on ToDo for the weekend to check on a few on the list so you don't have to, but that was some quick work!

Just a minor few small things left:

1) The left bar default dark grey (as mentioned) is a bit light with the red and "bites" - that's why I recommended going for a bit darker colour but just wanted to show what I mean here :)
![leftbar](https://user-images.githubusercontent.com/4711823/47713138-cc156180-dc39-11e8-8b81-d3ff96259fb2.png) 

3) The buttons are fine now, as the borders around are gone like in the default theme. Only small thing now is, that the :hover effect changes the background to a white or lighter gray, showing a "button/box" instead of just adding the underline effect. Nothing huge at all, just a minor thing left :)
![buttonbg](https://user-images.githubusercontent.com/4711823/47713319-5231a800-dc3a-11e8-97f6-fdc3d00b9d80.png)

7) Dropdown arrows: have a look at the small screenshot of the theme/layout theme.
![dropdown](https://user-images.githubusercontent.com/4711823/47713207-fc5d0000-dc39-11e8-8e62-2d48c2944808.png)
Those are the dropdowns but they are missing the down-arrow on the right. I saw in the CSS debugger, that the class had a z-index of 3, changing it to a lower (1) made them visible.

And on a small note: wouldn't it be consistent to make the toggles red, too, instead of leaving them violet like the default? ;)

Besides the theme overall is incredibly well done! Thanks so much again for making my stay at protonmail so much more enjoyable (to my eyes) 😄

**Comment by JeGr** [comment]
Another small one spotted:

![image](https://user-images.githubusercontent.com/4711823/48316736-ed862e00-e5e7-11e8-9b27-a57d8f9d535f.png)
* The "move to" or "add label" dropdown has this dark background instead of the light one as the "more" dropdown (with sorting etc.)

Fixed it by changing the .scrollbox-container from theme7 to white:
`.scrollbox-container{background-color:var(--white)!important;background-image:unset!important}`

**Comment by amdelamar** [comment]
Ok that should be it. The background on button links I left alone.
