### ISSUE TITLE
CSS colors problem at dashboard settings

### ISSUE THREAD

**Issue by mKoonrad** [amdelamar/pm-theme#48]
Theme used: Dark
Brave browser 0.59.35 Chromium 72.0.3626.81
Windows 10
ProtonMail web 3.15.16

Problem with white drop-down lists at dashboard settings. I can't read text on it. It should be dark like when I click on it. Pricing summary at the bottom should be also better.
![dashboard](https://user-images.githubusercontent.com/11725227/52667709-e5ed6280-2f11-11e9-8550-9941e0ecc745.png)

**Comment by amdelamar** [comment]
Ok should be fixed in latest version
