### ISSUE TITLE
Dark-style Background Image Theme

### ISSUE THREAD

**Issue by JeGr** [amdelamar/pm-theme#49]
## Environment
 * Theme used: BG-Image
 * Browser name and version: any
 * OS/Device version: any

## Describtion

I'd make a feature suggestion to include a dark-style version of the Background Image Theme just like e.g. the current GMail style with a little bigger search bar fonts, font-spacings etc.

**Comment by amdelamar** [comment]
Dark Background Image theme is do-able.

But pm-themes only change colors and shadows. Not fonts, spacings ,layout, icons, etc. But you're free to incorporate your own alongside any theme.

**Comment by amdelamar** [comment]
Sorry, don't have time to work on this. I also won't be updating the bg image theme to v4.0.0 when its released.
