### ISSUE TITLE
Update Flat theme for Protonmail version 3.7

### ISSUE THREAD

**Issue by ntimo** [amdelamar/pm-theme#5]
Hi their,
it would be really awesome if you could update the theme wo work with Protonmail 3.7 the new settings sidebar menu does requier some makeup (the back button) and the searchbar too. 

Thank you,
Timo

**Comment by amdelamar** [comment]
Thanks for the note. I need to fix this, and on all the others as well. Will get to it soon!

**Comment by amdelamar** [comment]
Ok, I fixed it for v3.7, in 6229574. I removed some older themes too. Not sure if anyone used those...
