### ISSUE TITLE
ProtonVPN icon color

### ISSUE THREAD

**Issue by frelind** [amdelamar/pm-theme#51]
## Your Environment
 * Theme used: (Dark / Flat / GM / BG-Image):
Flat
 * Browser name and version: 
Chrome 73.0.3683.103 
 * OS/Device version:  
Windows 10 Build 17763
## Describe the Problem
Proton VPN icon color does not match

![protonvpn](https://user-images.githubusercontent.com/10121588/56083667-66ecab80-5e28-11e9-84fa-f98a6b00c81f.PNG)

**Comment by amdelamar** [comment]
Should be fixed now.
