### ISSUE TITLE
Can't read folder names on dark theme on mobile

### ISSUE THREAD

**Issue by RaneWallin** [amdelamar/pm-theme#52]
## Your Environment
 * Theme used: (Dark / Flat / GM / BG-Image) Dark
 * Browser name and version: Chrome for mobile 73.0.3683.90
 * OS/Device version: android 9

## Describe the Problem
Using the dark theme on mobile the folder names are black on black

![Screenshot_20190419-143251_Chrome](https://user-images.githubusercontent.com/12719774/56445233-04286380-62b1-11e9-8dae-85842b0d6c3c.jpg)

**Comment by RaneWallin** [comment]
The selected folder is white on black, but the rest are black on black. The part of the page that is outside of the vp doesn't get the theme applied, but I assume that's a Chrome issue

**Comment by amdelamar** [comment]
Unfortunately these themes are mostly created for the desktop site. I don't personally use the mobile site at all. Hoping the PM team comes thru with dark theme on the mobile app soon.

I'll see if I ever have time to debug this on mobile later.

**Comment by amdelamar** [comment]
Sorry, don't have time to work on this. Hopefully v4.0.0 that's in beta can solve this with their own dark theme.
