### ISSUE TITLE
Dark Theme category and label pulldown have dark text

### ISSUE THREAD

**Issue by JeGr** [amdelamar/pm-theme#53]
## Your Environment
 * Theme used: Dark
 * Browser name and version: any (chrome, etc.)
 * OS/Device version: Win10x64

## Describe the Problem
Category and Label names when displayed in the pulldown menu are dark on dark (gray text instead of white).

![image](https://user-images.githubusercontent.com/4711823/58077305-8788ed80-7bac-11e9-8bce-878be023ad80.png)

If one gives the "ellipsis" class the additional attribute: var(--theme2)!important; it works but I haven't checked all instances yet if that does something bad anywhere else.

**Comment by JeGr** [comment]
Added 
`.ellipsis{color:var(--theme2)!important}`
at the end of the CSS as a workaround, seems to work fine ATM.

**Comment by JeGr** [comment]
BTW: Adding/removing the minified CSS almost constantly crashes chromium based browsers (chrome, opera) on Windows as they have problems to load/work with the long single-line-based paste of data in the form field. Breaking it up into multiple lines with less length seems way better for them to process the data. Have to insert the css with Edge or Firefox as others crash the tab it runs in.

**Comment by JeGr** [comment]
`.dropdown-folder-title, .dropdown-label-title, .dropdown-label-alsoArchive-txt{color:var(--theme5)!important}`
Adding that will also make category title, label title and "also archive" text more visible by using the theme color (violet).

![image](https://user-images.githubusercontent.com/4711823/58078913-219e6500-7bb0-11e9-8ed7-dcbfddf81999.png)

**Comment by amdelamar** [comment]
The labels and folder names should be fixed now.

If you're not able to use the Minified CSS, feel free to use the source:

https://github.com/amdelamar/pm-theme/tree/master/themes

Thanks!
