### ISSUE TITLE
My phone can't scan the QR code that enables 2FA authentication

### ISSUE THREAD

**Issue by guixxx** [amdelamar/pm-theme#54]
## Your Environment
 * Theme used: Dark
 * Browser name and version: Chromium 74
 * OS/Device version: Linux

## Describe the Problem

When I'm using the Dark theme, the QR code reader app (which in my case, is the one used by [andOTP](https://github.com/andOTP/andOTP)), can't read the QR code for shit, due to the dark background of the modal, probably:

![QR-before](https://user-images.githubusercontent.com/27077338/58755572-d5f78f80-84bc-11e9-8fb2-beaf7130dc21.png)

It could also be due to my phone's camera not being that good, but then I changed the background color of that modal to a bright color (white):

![QR-after](https://user-images.githubusercontent.com/27077338/58755575-db54da00-84bc-11e9-9fbc-4faec4f80f1b.png)

And the QR reader app was able to decode the image instantly...

**Comment by guixxx** [comment]
In case you don't want to disable your 2FA to find out where the modal is / or what CSS classes it uses, I have a screenshot that might help you:

![2019-06-01_22-39](https://user-images.githubusercontent.com/27077338/58755678-c8dba000-84be-11e9-9063-69d18eda2b58.png)

I've experimented using not-so-bright colors too, but the app still struggles to read the code... I think a white background just for the modal body is the way to go, but I'm not a designer so I'll leave it to you.

Thanks!

**Comment by amdelamar** [comment]
Thanks for filing. So the QRcode has black on white pixels. Did the dark theme change the white pixels to some other color? If not, then just the surrounding modal background color affected your apps ability to read the QRcode?

I'm not willing to disable my 2FA on my PM, just to get the modal to appear for me. The screenshot you provided while helpful, doesn't seem to contain identifying `id/class` for just the 2FA modal. `modal-*` is used in other areas and I don't want to modify them all. It would be great if there is an `id="2fa"` or something specific to add attributes to.

I think I'd have to create a second PM account just to test the 2FA modal box.

**Comment by guixxx** [comment]
>If not, then just the surrounding modal background color affected your apps ability to read the QRcode?

I think that's exactly what happens. While the modal background color is not completely black like the pixels in the QR code image, my camera doesn't seem to differentiate them, so they just blend in, making it impossible for the app to find the edges of the image.

I've download the HTML file of the 2FA modal, see if it helps you on tracking down the classes and stuff:

[2fa-protonmail.zip](https://github.com/amdelamar/pm-theme/files/3245127/2fa-protonmail.zip)

**Comment by amdelamar** [comment]
Sorry, don't have time to work on this. Hopefully v4.0.0 that's in beta can solve this with their own dark theme.
