### ISSUE TITLE
Include SPDX IDs in CSS files

### ISSUE THREAD

**Issue by oxr463** [amdelamar/pm-theme#56]
## Your Environment
 * Theme used: Any
 * Browser name and version: Any
 * OS/Device version: Any

## Describe the Problem

It would be great to include the license in the comment header like so,

```diff
  @charset "UTF-8";
  /*!
   * Custom Theme for ProtonMail v3.15.0
   * http://amdelamar.com/pm-theme/
+  * SPDX-License-Identifier: MIT
   */
```

See: https://spdx.org/ids

**Comment by amdelamar** [comment]
Never heard of the SPDX format.

I glanced at a few popular CSS libraries and they don't include this either.

```css
/*! bulma.io v0.7.5 | MIT License | github.com/jgthms/bulma */

/*!
 * Bootstrap v4.3.1 (https://getbootstrap.com/)
 * Copyright 2011-2019 The Bootstrap Authors
 * Copyright 2011-2019 Twitter, Inc.
 * Licensed under MIT (https://github.com/twbs/bootstrap/blob/master/LICENSE)
 */

/**
 * Foundation for Sites by ZURB
 * Version 6.5.1
 * foundation.zurb.com
 * Licensed under MIT Open Source
 */

/*!
 * Milligram v1.3.0
 * https://milligram.github.io
 *
 * Copyright (c) 2018 CJ Patoilo
 * Licensed under the MIT license
 */

/*! normalize.css v8.0.0 | MIT License | github.com/necolas/normalize.css */
```

Maybe its just a awareness issue. But I guess it doesn't hurt to simply add it.

**Comment by oxr463** [comment]
SPDX is rather new; I guess I could've just asked to include the license in the files. One advantage of using SPDX is that they are machine parsable, and standardized.
