### ISSUE TITLE
Update for Protonmail v4.0.0

### ISSUE THREAD

**Issue by amdelamar** [amdelamar/pm-theme#58]
Need to update for v4.0.0
Would be good to start from scratch, in terms of reusing old CSS styling.

**Comment by amdelamar** [comment]
Customizing the themes is easier in v4, but I hope they have an official dark mode, (and mobile apps too). Then I wouldn't need to maintain this project anymore. They have semi-working default themes already: https://design-system-beta.netlify.com/themes/

"Light" theme for example is simple and easy to edit:
```
/* 
 * Light theme
 */
:root {
  --main-bg-color: #f6f7fa;
  --secondary-bg-color: #fff;
  --bgcolor-searchbox-field: #fff;
  --bgcolor-spacebar: rgba(0, 0, 0, 0.05);
  --bgcolor-aside-link: #e3e4e7;
  --bgcolor-toolbar: #f6f7fa;
  --fillcolor-logo: #657ee4;
  --fillcolor-icons: #262a33;
  --color-nav-link: #262a33;
  --color-nav-active: #526ee0;
  --color-standard-text: #262a33;
  --boxshadow-main: 0 0 15px 0 rgba(0, 0, 0, 0.1); }
```

Only glaring improvement to be made is a dark theme that changes the `.main, .main-area` colors from white to something else. But without any nice root `var`s to set, its still cumbersome at the moment. Hopefully they will update those classes to use replaceable values (`background: var(--bgcolor-main,#262a33);`) soon. But again, if they improve those areas, then we most likely don't need this project's dark or flat theme anymore.

As for the "gm-theme" and "background-image-theme", I will not spend time updating them to v4.

**Comment by csalmeida** [comment]
This is great, the PM team is planning to add dark mode as part of the `v4` release too. 🙂

**Comment by amdelamar** [comment]
PM released a Dark Mode for the beta web app. https://twitter.com/ProtonMail/status/1235235424064466944

**Comment by Alienmoon** [comment]
Seems PM as taken Dark mode away in PM appearance settings,... 
So I came to express my appreciation for this work you've done.

Thank you

**Comment by amdelamar** [comment]
Closing out as this is repo is archived and PM does not support custom css styling natively. Although users can probably find Firefox Plugins / Chrome Extensions to do this, i.e. Stylish.
