### ISSUE TITLE
V4.0.0 - lots of CSS validation errors

### ISSUE THREAD

**Issue by qtumev** [amdelamar/pm-theme#59]
## Your Environment
 * Theme used: 4.0.0
 * Browser name and version: Firefox 70
 * OS/Device version: macOS Mojave 10.14.6

## Describe the Problem

Using a CCS validator results in multiple errors.
ex: https://codebeautify.org/cssvalidate/

Thank you for the time and effort.
Maybe a "classic" theme for the lovers of v3 when v4 will hit everyone ?

**Comment by amdelamar** [comment]
Hi, thanks but as far as CSS validation goes, I'm not really concerned. These are simple themes on top of some pre-existing CSS. I think CSS validation might be better suited for large frameworks like Bootstrap, etc, instead.

**Comment by amdelamar** [comment]
If you find a bug, or have cross-browser issues when using these themes, please post those. :)
