### ISSUE TITLE
<code> tags inside email content are unreadable

### ISSUE THREAD

**Issue by guihkx** [amdelamar/pm-theme#61]
## Your Environment
 * Theme used: Dark
 * Browser name and version: Chrome 80
 * OS/Device version: Linux

## Describe the Problem
The text color of `<code>` tags is white on the dark theme:

https://github.com/amdelamar/pm-theme/blob/810ecc160695c0b6a266001efd5215585c05c8ee/themes/pm-dark-theme.css#L1038-L1040

So, due to the white background of the container that holds the email body, anything inside `<code>` tags gets invisible:

![image](https://user-images.githubusercontent.com/626206/74352009-a95b7d80-4d96-11ea-8eb1-5491c905cdd2.png)

**Comment by amdelamar** [comment]
Darn. Ok should be easy to fix by filtering white as default and say, black, for if in message-view.
Will try and put up a fix

**Comment by amdelamar** [comment]
I've found a code tag in the PM UI, under Settings > Security > Session Management. So it doesn't look good when I change code to `black`.

I'll set it to `inherit` which should work for most situations.
