### ISSUE TITLE
Add New Themes

### ISSUE THREAD

**Issue by VPCAmber** [amdelamar/pm-theme#63]
## Your Environment
 * Theme used: Nord
 * Browser name and version: Chrome Version 90.0.4430.218 (Official Build) (64-bit)
 * OS/Device version: Acer Chromebook 315

**Comment by amdelamar** [comment]
Closing out as this is repo is archived and PM does not support custom css styling natively. Although users can probably find Firefox Plugins / Chrome Extensions to do this, i.e. Stylish.

Thank you for your interest.
